### ISSUE TITLE
Server update speed?

### ISSUE THREAD

**Issue by NilesDev** [omnivector-solutions/jobbergate-cli#25]
This may be more appropriate to put in the -api repository, but...
Sometimes when I create an application and quickly try to use it, it seems like the application is registered but not "filled in".
So it tries to get the files and runs into trouble because they can't be found yet. 
When repeating the same "create-job-script" command a few seconds later, everything is fine.
Example below.  

```
(jg2venv) [nsxbxc@login2 Test_03]$ jg create-application -n StarCCMpart -a ~/jobberapplications/jobberapplications/apps/starccm2/
-----------------------  -----------
id                       94
application_name         StarCCMpart
application_description
application_owner        9
-----------------------  -----------
(jg2venv) [nsxbxc@login2 Test_03]$ jg create-job-script -i 94
Traceback (most recent call last):
  File "/home/nsxbxc/updated_apps/jg2venv/bin/jobbergate-cli", line 11, in <module>
  File "/home/nsxbxc/updated_apps/jg2venv/lib64/python3.6/site-packages/click/core.py", line 829, in __call__
  File "/home/nsxbxc/updated_apps/jg2venv/lib64/python3.6/site-packages/click/core.py", line 782, in main
  File "/home/nsxbxc/updated_apps/jg2venv/lib64/python3.6/site-packages/click/core.py", line 1259, in invoke
  File "/home/nsxbxc/updated_apps/jg2venv/lib64/python3.6/site-packages/click/core.py", line 1066, in invoke
  File "/home/nsxbxc/updated_apps/jg2venv/lib64/python3.6/site-packages/click/core.py", line 610, in invoke
  File "/home/nsxbxc/updated_apps/jg2venv/lib64/python3.6/site-packages/click/decorators.py", line 33, in new_func
  File "/home/nsxbxc/updated_apps/tmp/jobbergate-cli/jobbergate_cli/main.py", line 272, in create_job_script
  File "/home/nsxbxc/updated_apps/tmp/jobbergate-cli/jobbergate_cli/jobbergate_api_wrapper.py", line 146, in wrapper
  File "/home/nsxbxc/updated_apps/tmp/jobbergate-cli/jobbergate_cli/jobbergate_api_wrapper.py", line 391, in create_job_script
  File "/usr/lib64/python3.6/pathlib.py", line 1215, in write_text
    with self.open(mode='w', encoding=encoding, errors=errors) as f:
  File "/usr/lib64/python3.6/pathlib.py", line 1183, in open
    opener=self._opener)
  File "/usr/lib64/python3.6/pathlib.py", line 1037, in _opener
    return self._accessor.open(self, flags, mode)
  File "/usr/lib64/python3.6/pathlib.py", line 387, in wrapped
    return strfunc(str(pathobj), *args)
FileNotFoundError: [Errno 2] No such file or directory: '/home/nsxbxc/.jobbergate/jobbergate.py'

```

**Comment by zsinx6** [comment]
This one will be fixed with the jobbergateapi2
